### ISSUE TITLE
Todo for Ver 2.0.0

### ISSUE THREAD

**Issue by kenju** [kenju/instagram_js_filter#2]
# Improvement

## Feature

* [x] Improvement in performance 
* [x] Hide canvas-usage logic
* [x] support options for filter effects

## Testing

* [x] Implement Unit Testing

## Build

* [x] Build-task to minify/optimise demo site (js, css, and other assets site)

## Workflows / Docs / Others

* [x] Implement cc styles
* [x] Implement CI environment
* [x] Implement ESLint workflow
* [x] Enhancement in Contribution guides
* [x] Create `/example` folder for usage examples
* [x] Minimum API documents in README.md

**Comment by kenju** [comment]
JSDoc seems charm

http://google.github.io/google-api-nodejs-client/2.1.7/analytics.html

**Comment by kenju** [comment]
UglifyJS2 for minify

https://github.com/mishoo/UglifyJS2

**Comment by kenju** [comment]
TODO lists is split into each issues
